### ISSUE TITLE
Install command in quickstart seems incorrect? 

### ISSUE THREAD

**Issue by richardklafter** [toverainc/willow-docs#15]
Quick start has the command.

`docker run --detach --name=willow-application-server --pull=always --network=host --restart=unless-stopped --volume=was-storage:/app/storage ghcr.io/toverainc/willow-application-server`

Few issues:
* It is using `--network=host` [which only works on linux?](https://docs.docker.com/network/drivers/host/) and is pretty nonstandard for self host software like this. E.g. I think Portainer has issues with it?
* Port 8501 no longer serves the UI but maybe it used to? I think docs need updated to correct port of 8502?
* Why not just use `-p 8502:8502`? The docker compose file at https://github.com/toverainc/willow-application-server/blob/main/docker-compose.yml works well.

**Comment by kristiankielhofner** [comment]
I updated the docs to reflect the new port number for the UI.

We use ``--network=host``` so the container can try to determine the actual host/network IP address and display it to the user (among other things). You are correct in that it's not strictly required and I've confirmed it does work without host network mode.

We also use host networking because we plan to support auto-discovery of WAS and connected devices in the future.

**Comment by richardklafter** [comment]
Sounds good! Thanks!
